name: is2-book-env
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - argon2-cffi=20.1.0=py37haf1e3a3_1
  - attrs=20.1.0=py_0
  - backcall=0.2.0=py_0
  - basemap=1.2.0=py37h0acbc05_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - bokeh=2.2.1=py37_0
  - brotlipy=0.7.0=py37haf1e3a3_1000
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2020.7.22=0
  - cartopy=0.16.0=py37h9263bd1_0
  - certifi=2020.6.20=py37_0
  - cffi=1.14.2=py37hed5b41f_0
  - cftime=1.2.1=py37hf1fa96c_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.1=py37hddc9c9b_0
  - curl=7.71.1=hb0a8c7a_1
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h1de35cc_0
  - dask=2.25.0=py_0
  - dask-core=2.25.0=py_0
  - dbus=1.13.16=h18a8e69_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.25.0=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.9=hb1e8313_2
  - freetype=2.10.2=ha233b18_0
  - fsspec=0.8.0=py_0
  - geos=3.6.2=h5470d99_2
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.65.0=hc5f4afa_0
  - h5py=2.10.0=py37h3134771_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.4=hfa1e0ec_0
  - heapdict=1.0.1=py_0
  - icu=58.2=h0a44026_3
  - idna=2.10=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2019.4=233
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.18.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.2=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py37_0
  - kiwisolver=1.2.0=py37h04f5b5a_0
  - krb5=1.18.2=h75d18d8_0
  - lcms2=2.11=h92f6f08_0
  - libcurl=7.71.1=h8a08a2b_1
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libnetcdf=4.7.3=he3b6227_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libssh2=1.9.0=ha12b0ac_1
  - libtiff=4.1.0=hcb84e12_1
  - libxml2=2.9.10=h3b9e6c8_1
  - libxslt=1.1.34=h83b36ba_0
  - locket=0.2.0=py37_1
  - lxml=4.5.2=py37h63b7cb6_0
  - lz4-c=1.9.2=hb1e8313_1
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h181983e_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.1.0=py37hc64f4ea_0
  - mkl_random=1.1.1=py37h959d312_0
  - more-itertools=8.5.0=py_0
  - msgpack-python=1.0.0=py37h04f5b5a_1
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=h0a44026_1
  - netcdf4=1.5.3=py37h28545a2_0
  - notebook=6.1.1=py37_0
  - numpy=1.19.1=py37h3b9f5b6_0
  - numpy-base=1.19.1=py37hcfb5961_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h1de35cc_0
  - owslib=0.18.0=py_0
  - packaging=20.4=py_0
  - pandas=1.1.1=py37hb1e8313_0
  - pandoc=2.10.1=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.2.0=py37ha54b6ba_0
  - pip=20.2.2=py37_0
  - proj4=5.0.1=h1de35cc_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.7=py_0
  - prompt_toolkit=3.0.7=0
  - psutil=5.7.2=py37haf1e3a3_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.20=py_2
  - pyepsg=0.4.0=py37_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyproj=1.9.5.1=py37h833a5d7_1
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.16.0=py37h1de35cc_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37_0
  - python=3.7.9=h26836e1_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37haf1e3a3_1
  - pyzmq=19.0.1=py37hb1e8313_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.6=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - requests=2.24.0=py_0
  - scipy=1.5.2=py37h912ce22_0
  - send2trash=1.5.0=py37_0
  - setuptools=49.6.0=py37_0
  - shapely=1.6.4=py37h20de77a_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.15.0=py_0
  - sortedcontainers=2.2.2=py_0
  - sqlite=3.33.0=hffcf06c_0
  - tblib=1.7.0=py_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h1de35cc_1
  - traitlets=4.3.3=py37_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py37_0
  - xarray=0.16.0=py_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.2=hb1e8313_2
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
  - pip:
    - alabaster==0.7.12
    - argcomplete==1.12.0
    - async-generator==1.10
    - babel==2.8.0
    - beautifulsoup4==4.9.1
    - boto==2.49.0
    - colorama==0.4.3
    - crcmod==1.7
    - docutils==0.16
    - fasteners==0.15
    - gcs-oauth2-boto-plugin==2.7
    - ghp-import==1.0.0
    - gitdb==4.0.5
    - gitpython==3.1.8
    - google-apitools==0.5.31
    - google-reauth==0.1.0
    - gsutil==4.53
    - httplib2==0.18.1
    - imagesize==1.2.0
    - jupyter-book==0.8.0
    - jupyter-cache==0.4.1
    - jupyter-sphinx==0.3.1
    - latexcodec==2.0.1
    - libsass==0.20.1
    - markdown-it-py==0.5.3
    - mock==2.0.0
    - monotonic==1.5
    - myst-nb==0.10.0
    - myst-parser==0.12.8
    - nbclient==0.5.0
    - nbdime==2.0.0
    - nest-asyncio==1.4.0
    - oauth2client==4.1.3
    - oset==0.1.3
    - pbr==5.5.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybtex==0.22.2
    - pybtex-docutils==0.2.2
    - pydata-sphinx-theme==0.3.2
    - pyu2f==0.1.4
    - retry-decorator==1.1.1
    - rsa==4.6
    - smmap==3.0.4
    - snowballstemmer==2.0.0
    - soupsieve==2.0.1
    - sphinx==3.2.1
    - sphinx-book-theme==0.0.36
    - sphinx-comments==0.0.3
    - sphinx-copybutton==0.3.0
    - sphinx-panels==0.4.1
    - sphinx-thebe==0.0.7
    - sphinx-togglebutton==0.2.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-bibtex==1.0.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sqlalchemy==1.3.19
prefix: /Users/nicolekeeney/opt/anaconda3/envs/is2-book-env

